name: Checks

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      INFURA_KEY: ${{ secrets.INFURA_KEY }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.0

      - name: Fetch packages
        run: pnpm fetch


      - name: Install Dependencies
        run: pnpm install -r --offline

      - name: Run tests
        run: npm run test

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - uses: pnpm/action-setup@v2
        with:
          version: 7.18.0

      - name: Fetch packages
        run: pnpm fetch


      - name: Install Dependencies
        run: pnpm install -r --offline

      - name: Run linter
        run: npm run lint
